### ISSUE TITLE
[REQ] CI - 테스트 추가

### ISSUE THREAD

**Issue by ypd06021** [Mini-Team-6/Mini-Team-6-Backend#4]
## 기능

CI (GithubActions) 기능 추가
- main 과 develop 브랜치에 Pull requests, merge 시 테스트 실행
- 테스트 결과 리포트(+  슬랙 알림)
- 테스트 실패시 pr에 코멘트를 달아줌, 테스트 실패시 merge 불가
-----
<br>
<br>
<br>

## 설명
![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/c61e3e77-06a8-403a-91c2-0c3e93601359)
의 Actions 탭에서 테스트 실행 결과를 상세 조회 가능합니다.

<br>
<br>
<br>

상세 조회 시 보여지는 아래 항목을 클릭하면 
![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/5f39f41e-c880-4b7f-980f-833cc7e08c77)

<br>
<br>
<br>

아래와 같이 뜨는 탭을 클릭하여 결과를 확인할 수 있습니다. (테스트 실패 원인을 알 수 있어요)

![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/7c3849b3-fb5c-4c14-a167-56ebb698670c)

<br>

build and test project 네모 탭 클릭 ..

<br>
<br>

<br>

![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/507f6145-a21b-479b-9173-e7e1ecd7327a)

여기서 자세한 결과를 확인할 수도 있고, 테스트가 수행되는걸 실시간으로도 확인할 수 있습니다
<br>
<br>

<br>
수행 세부 결과를 보고싶다면
클릭 ..
<br>
<br>

![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/ce3a80b7-9e98-4de1-9d35-4c5a53df3c12)

<br>
<br>

테스트 코드가 많아지면 보통 테스트 수행되는데 1~2분 정도걸리기도 해요

어쨌든, 테스트 수행의 결과는 아래처럼 pr이나 커밋에서도 확인하실 수 있고, 저 테스트 결과 이모지(?)를 클릭해서 바로 상세 조회도 가능합니당

<br>

![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/69bcb58c-fb0e-469c-b235-ebdc8f89fbf7)

<br>
<br>

![image](https://github.com/Mini-Team-6/Mini-Team-6-Backend/assets/78525973/75300a09-0ccb-4710-9780-4908778d7aa3)

**Comment by yuhyun1** [comment]
👍
